# cloudbuild.yml — 修正版（TOKEN のテンプレート衝突を回避、IMAGE_TAG をエスケープ）
steps:
  # --- ステップ0: デバッグ（オプション）: Build SA からの Firebase API 応答を確認 ---
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Debug: Firebase project metadata (build-SA view)"
    entrypoint: "bash"
    args:
      - -c
      - |
        echo "=== Debug: firebase project metadata (as Build SA) ==="
        gcloud --version || true
        echo "Calling Firebase projects.get..."
        curl -s -H "Authorization: Bearer $(gcloud auth print-access-token)" "https://firebase.googleapis.com/v1beta1/projects/${PROJECT_ID}" | head -c 2000 || true
        echo "Calling Firebasestorage buckets list..."
        curl -s -H "Authorization: Bearer $(gcloud auth print-access-token)" "https://firebasestorage.googleapis.com/v1/projects/${PROJECT_ID}/buckets" | head -c 2000 || true

  # --- ステップ1: フロントエンドのビルド (app) ---
  - name: "ghcr.io/cirruslabs/flutter:stable"
    id: "Build Frontend"
    entrypoint: "bash"
    args:
      - -c
      - |
        if [[ "${_DEPLOY_TARGET}" == "all" || "${_DEPLOY_TARGET}" == "app" ]]; then
          echo ">>> Building Flutter web app..."
          cd app
          flutter pub get
          flutter build web --release
        else
          echo ">>> Skipping Flutter build for target: ${_DEPLOY_TARGET}"
        fi

  # --- ステップ2: Firebase Rules のデプロイ ---
  - name: "us-docker.pkg.dev/firebase-cli/us/firebase:14.15.2"
    id: "Deploy Firebase Rules"
    entrypoint: "bash"
    args:
      - -c
      - |
        if [[ "${_DEPLOY_TARGET}" == "all" || "${_DEPLOY_TARGET}" == "rules" ]]; then
          echo ">>> Firebase CLI version:"
          firebase --version || true
          echo ">>> Deploying Firestore and Storage rules..."
          firebase deploy --only firestore:rules,storage --project=${PROJECT_ID}
        else
          echo ">>> Skipping Firebase Rules deployment for target: ${_DEPLOY_TARGET}"
        fi

  # --- ステップ3: Cloud Functions Gen2 のデプロイ ---
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Deploy Cloud Functions"
    entrypoint: "bash"
    args:
      - -c
      - |
        if [[ "${_DEPLOY_TARGET}" == "all" || "${_DEPLOY_TARGET}" == "functions" ]]; then
          echo ">>> Deploying Cloud Functions gen2"
          gcloud --version
          gcloud functions deploy ${_FUNCTION_NAME} \
            --gen2 \
            --runtime=python313 \
            --region=${_REGION} \
            --source=./functions \
            --entry-point=generate_signed_url \
            --trigger-http \
            --project=${PROJECT_ID} \
            --set-env-vars="AUDIO_UPLOAD_BUCKET=${_AUDIO_UPLOAD_BUCKET},FIRESTORE_COLLECTION=${_FIRESTORE_COLLECTION}"
        else
          echo ">>> Skipping Cloud Functions deployment for target: ${_DEPLOY_TARGET}"
        fi

  # --- ステップ4: Backend イメージをビルドして Artifact Registry へプッシュ ---
  - name: "gcr.io/cloud-builders/docker"
    id: "Build backend image"
    entrypoint: "bash"
    args:
      - -c
      - |
        if [[ "${_DEPLOY_TARGET}" == "all" || "${_DEPLOY_TARGET}" == "backend" ]]; then
          IMAGE_TAG="${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_BACKEND_SERVICE_NAME}:${SHORT_SHA}"
          echo ">>> Building image $${IMAGE_TAG}"
          docker build -t "$${IMAGE_TAG}" backend
          echo ">>> Pushing image $${IMAGE_TAG}"
          docker push "$${IMAGE_TAG}"
        fi

  # --- ステップ5: Cloud Run へデプロイ ---
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Deploy Backend to Cloud Run"
    entrypoint: "bash"
    args:
      - -c
      - |
        if [[ "${_DEPLOY_TARGET}" == "all" || "${_DEPLOY_TARGET}" == "backend" ]]; then
          IMAGE_TAG="${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_BACKEND_SERVICE_NAME}:${SHORT_SHA}"
          echo ">>> Deploying to Cloud Run: ${_BACKEND_SERVICE_NAME}"
          gcloud run deploy ${_BACKEND_SERVICE_NAME} \
            --image "$${IMAGE_TAG}" \
            --platform managed \
            --region ${_REGION} \
            --service-account ${_BACKEND_SA_NAME}@${PROJECT_ID}.iam.gserviceaccount.com \
            --no-allow-unauthenticated \
            --set-env-vars="GOOGLE_CLOUD_PROJECT_ID=${PROJECT_ID},AUDIO_UPLOAD_BUCKET=${_AUDIO_UPLOAD_BUCKET},PROCESSED_AUDIO_BUCKET=${_PROCESSED_AUDIO_BUCKET},GENERATED_IMAGE_BUCKET=${_GENERATED_IMAGE_BUCKET},FIRESTORE_COLLECTION=${_FIRESTORE_COLLECTION},SESSION_SERVICE=inmemory" \
            --project=${PROJECT_ID}
        fi

  # --- ステップ6: Eventarc トリガーの設定（gcloud） ---
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Configure Eventarc Trigger"
    entrypoint: "bash"
    args:
      - -c
      - |
        if [[ "${_DEPLOY_TARGET}" == "all" || "${_DEPLOY_TARGET}" == "backend" || "${_DEPLOY_TARGET}" == "trigger" ]]; then
          echo ">>> Configuring Eventarc trigger..."
          gcloud run services add-iam-policy-binding ${_BACKEND_SERVICE_NAME} \
            --region=${_REGION} \
            --member="serviceAccount:${_TRIGGER_SA_NAME}@${PROJECT_ID}.iam.gserviceaccount.com" \
            --role="roles/run.invoker" --project=${PROJECT_ID} > /dev/null
          if ! gcloud eventarc triggers describe ${_TRIGGER_NAME} --location=${_REGION} --project=${PROJECT_ID} >/dev/null 2>&1; then
            echo "Trigger ${_TRIGGER_NAME} not found. Creating..."
            gcloud eventarc triggers create ${_TRIGGER_NAME} \
              --location=${_REGION} \
              --destination-run-service=${_BACKEND_SERVICE_NAME} \
              --destination-run-region=${_REGION} \
              --event-filters="type=google.cloud.storage.object.v1.finalized" \
              --event-filters="bucket=${_AUDIO_UPLOAD_BUCKET}" \
              --service-account=${_TRIGGER_SA_NAME}@${PROJECT_ID}.iam.gserviceaccount.com \
              --project=${PROJECT_ID}
          else
            echo "Trigger ${_TRIGGER_NAME} already exists."
          fi
        fi

  # --- ステップ7: Firebase Hosting（frontend）デプロイ ---
  - name: "us-docker.pkg.dev/firebase-cli/us/firebase:latest"
    id: "Deploy Frontend to Hosting"
    entrypoint: "bash"
    args:
      - -c
      - |
        if [[ "${_DEPLOY_TARGET}" == "all" || "${_DEPLOY_TARGET}" == "app" ]]; then
          echo ">>> Firebase CLI version:"
          firebase --version || true
          echo ">>> Deploying to Firebase Hosting..."
          firebase deploy --only hosting --project=${PROJECT_ID}
        fi

timeout: 1200s

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _DEPLOY_TARGET: "all"
  _REGION: "asia-northeast1"
  _BACKEND_SERVICE_NAME: "coco-ai-backend"
  _FUNCTION_NAME: "generate_signed_url"
  _BACKEND_SA_NAME: "coco-ai-backend-sa"
  _TRIGGER_SA_NAME: "coco-ai-eventarc-invoker"
  _TRIGGER_NAME: "trigger-coco-ai-storage"
  _FIRESTORE_COLLECTION: "jobs"
  _ARTIFACT_REGISTRY_REPO: "coco-ai"
  _AUDIO_UPLOAD_BUCKET: "coco-ai-input-audio"
  _PROCESSED_AUDIO_BUCKET: "coco-ai-output-narrations"
  _GENERATED_IMAGE_BUCKET: "coco-ai-output-images"
